package com.example.organizadoria.financeiro.ui;
import android.widget.*;
import com.example.organizadoria.ApiService;
import com.example.organizadoria.AppSession;
import com.example.organizadoria.BuildConfig;
import com.example.organizadoria.RemoteCommandCodec;
import com.example.organizadoria.financeiro.domain.*;
import com.example.organizadoria.financeiro.network.CdiRepository;
import com.google.android.material.button.MaterialButton;
import com.google.android.material.textfield.TextInputEditText;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import retrofit2.*;
import retrofit2.converter.gson.GsonConverterFactory;
import java.util.*;
import static com.example.organizadoria.financeiro.domain.FinanceState.*;
import static com.example.organizadoria.financeiro.domain.FinanceEngine.*;
import static com.example.organizadoria.financeiro.ui.FinanceUi.*;
/** Interpreta e apresenta uma prévia; grava apenas após confirmação explícita. */
final class FinanceAssistant {
 private final FinanceFragment f;private final LinearLayout output;private final TextInputEditText input;private final MaterialButton analyze;private final String uid;
 private Call<JsonObject> request;private boolean closed,busy;
 FinanceAssistant(FinanceFragment fragment,LinearLayout p){
  f=fragment;uid=AppSession.uid(f.requireContext());eyebrow(p,"MENOS CAMPOS. MAIS CLAREZA.");add(p,text(p.getContext(),"Conte o que\nquer organizar.",28,WHITE,true),12);note(p,"Uma frase basta. Você revisa os valores antes de confirmar.");Form form=new Form(p.getContext());input=form.field("command","O que aconteceu?",f.assistantText,android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);input.setSingleLine(false);input.setMinLines(3);input.setMaxLines(7);FinanceOnboarding.watch(input,this::textChanged);form.scroll.removeView(form.body);add(p,form.body,12);analyze=button(p,"Revisar com o Cogni",this::analyze,true);output=column(p.getContext());add(p,output,16);section(p,"Pode falar assim",null,null);button(p,"Gastei R$40 no corte",()->example("Gastei R$40 no corte"),false);button(p,"Recebo R$3.000 todo dia 5",()->example("Todo dia 5 recebo R$3.000 e quero investir R$500 por mês"),false);button(p,"Tenho R$8.000 a 100% do CDI",()->example("Tenho R$8.000 a 100% do CDI e aporto R$500 por mês por 5 anos"),false);
  note(p,BuildConfig.LOCAL_ONLY?"Modo local: exemplos interpretados no aparelho. A IA conectada e o CDI automático estão na variante connected.":BuildConfig.GROQ_API_KEY.trim().isEmpty()?"IA remota não configurada nesta instalação. Os exemplos são interpretados no aparelho; o CDI continua disponível.":"Sua frase é interpretada pela IA conectada. Nenhuma movimentação é confirmada sozinha.");
 }
 private void textChanged(String value){f.assistantText=value;f.assistantOperation=null;if(output!=null)output.removeAllViews();}
 private void example(String value){if(busy)return;input.setText(value);input.setSelection(input.length());input.requestFocus();}
 private boolean active(){return !closed&&f.isAdded()&&f.getView()!=null&&Objects.equals(uid,AppSession.uid(f.requireContext()));}
 private void busy(boolean value){busy=value;input.setEnabled(!value);analyze.setEnabled(!value);analyze.setText(value?"Preparando sua prévia…":"Revisar com o Cogni");}
 private void reveal(){output.post(()->{if(active()){ScrollView scroll=f.getView().findViewById(com.example.organizadoria.R.id.financeScroll);scroll.smoothScrollTo(0,output.getTop());}});}
 private void error(String message){if(!active())return;busy(false);output.removeAllViews();note(card(output),message);reveal();}
 private void analyze(){
  if(busy)return;android.view.inputmethod.InputMethodManager keyboard=(android.view.inputmethod.InputMethodManager)f.requireContext().getSystemService(android.content.Context.INPUT_METHOD_SERVICE);if(keyboard!=null)keyboard.hideSoftInputFromWindow(input.getWindowToken(),0);
  String text=input.getText().toString().trim();if(text.isEmpty()||text.length()>2500){error("Conte o valor e o que deseja fazer, em até 2.500 caracteres.");return;}if(f.assistantOperation==null)f.assistantOperation=id();output.removeAllViews();busy(true);
  try{if(InvestmentDraft.accepts(text)){InvestmentDraft draft=InvestmentDraft.parse(text);if(BuildConfig.LOCAL_ONLY){busy(false);investment(draft);}else new CdiRepository(f.requireContext()).refresh(false,(quote,message)->{if(!active())return;f.cdi=quote;f.cdiError=message;busy(false);try{investment(draft);}catch(Exception e){error(e.getMessage());}});return;}
   if(BuildConfig.LOCAL_ONLY||BuildConfig.GROQ_API_KEY.trim().isEmpty()){preview(LocalCommandParser.parse(text,f.today()));return;}
   JsonArray messages=new JsonArray();JsonObject system=new JsonObject();system.addProperty("role","system");system.addProperty("content",RemoteCommandCodec.prompt(f.today())+" Esta é exclusivamente a área Financeiro. Não crie TASK nem altere Agenda. Se não for financeiro, retorne [].");messages.add(system);JsonObject user=new JsonObject();user.addProperty("role","user");user.addProperty("content",text);messages.add(user);JsonObject body=new JsonObject();body.addProperty("model","openai/gpt-oss-120b");body.addProperty("temperature",0);body.add("messages",messages);
   ApiService api=new Retrofit.Builder().baseUrl("https://api.groq.com/").addConverterFactory(GsonConverterFactory.create()).build().create(ApiService.class);request=api.mandarParaIA("Bearer "+BuildConfig.GROQ_API_KEY.trim(),body);request.enqueue(new Callback<JsonObject>(){public void onResponse(Call<JsonObject> call,Response<JsonObject> response){if(!active())return;try{if(!response.isSuccessful()||response.body()==null)throw new IllegalStateException("A IA não respondeu (HTTP "+response.code()+"). Seu texto continua aqui.");preview(RemoteCommandCodec.parse(response.body().getAsJsonArray("choices").get(0).getAsJsonObject().getAsJsonObject("message").get("content").getAsString(),f.today()));}catch(Exception e){error(e.getMessage());}}public void onFailure(Call<JsonObject> call,Throwable failure){if(!call.isCanceled())error("Não foi possível conectar à IA. Seu texto foi preservado.");}});
  }catch(Exception e){error(e.getMessage());}
 }
 private static void sameRevision(FinanceState state,long revision){if(state.revision!=revision)throw new IllegalStateException("Seu financeiro mudou. Toque em ‘Revisar com o Cogni’ para atualizar a prévia.");}
 private void preview(List<OrganizerCommand> commands){
  if(!active())return;int simulations=0;for(OrganizerCommand c:commands)if(c.action==OrganizerCommand.Action.SIMULATE||c.action==OrganizerCommand.Action.REQUIRED_CONTRIBUTION)simulations++;
  if(simulations>0){if(simulations!=commands.size()){error("Faça a simulação separadamente do registro para conferir cada resultado.");return;}simulate(commands);return;}busy(false);FinanceState before=f.state(),after=before.copy();String operation=f.assistantOperation,today=f.today();
  try{for(OrganizerCommand c:commands)if(c.action==OrganizerCommand.Action.TASK)throw new IllegalArgumentException("Este espaço cuida do dinheiro. Para compromissos, use a Agenda.");List<String> messages=CommandRouter.apply(after,commands,operation,today);validateState(after);output.removeAllViews();LinearLayout box=hero(output);eyebrow(box,"PRÉVIA · AINDA NÃO SALVA");reveal();for(String message:messages)note(box,message);Summary a=summarize(before,today),b=summarize(after,today);row(box,"Disponível",Money.format(a.available)+" antes",Money.format(b.available),CYAN,null);note(box,"A prévia ainda não foi salva.");button(box,"Confirmar registro",()->{Form review=new Form(f.requireContext());for(String message:messages)note(review.body,message);review.dialog("Confirmar estes dados?","Confirmar",d->f.mutate(state->{sameRevision(state,before.revision);CommandRouter.apply(state,commands,operation,today);},d,()->{f.assistantText="";f.assistantOperation=null;f.home();}));},true);
  }catch(CommandRouter.AmbiguousMatch match){String[] labels=new String[match.forecastIds.size()];for(int i=0;i<labels.length;i++){Forecast plan=forecast(before,match.forecastIds.get(i));labels[i]=plan.title+" · "+Money.format(remaining(before,plan));}FinanceForms.alert(f,"Qual previsão você quer confirmar?").setItems(labels,(d,index)->{commands.get(match.commandIndex).targetId=match.forecastIds.get(index);preview(commands);}).setNegativeButton("Voltar",null).show();}catch(Exception e){error(e.getMessage());}
 }
 private void investment(InvestmentDraft draft){
  if(!active())return;output.removeAllViews();FinanceState current=f.state();LinearLayout box=hero(output);eyebrow(box,"INVESTIMENTO IDENTIFICADO");reveal();add(box,text(box.getContext(),Money.format(draft.amount),30,WHITE,true),8);pill(box,FinanceInvestments.percent(draft.cdiPercent)+" do CDI",CYAN);if(draft.percentageAssumed)note(box,"Usei 100% do CDI como hipótese. Confira o percentual contratado antes de confirmar.");
  if(f.cdi!=null){double annual=InvestmentProjection.annualFromDaily(f.cdi.dailyPercent,draft.cdiPercent);long monthly=draft.monthlySpecified?draft.monthly:0;double[] values=InvestmentProjection.series(draft.amount,monthly,annual,draft.months),capital=InvestmentProjection.capital(draft.amount,monthly,draft.months);note(box,"Em "+draft.months+" meses, com "+Money.format(monthly)+"/mês: "+Money.format(Math.round(values[draft.months]*100))+" brutos estimados.");add(box,new FinanceChart(box.getContext(),values,capital,null,null),8);note(box,"CDI observado em "+FinanceScreens.displayDate(f.cdi.date)+", mantido constante. Base 252 dias úteis/ano. Sem impostos, custos ou inflação. Retorno não garantido.");if(f.cdi.stale(f.today()))pill(box,"Taxa antiga: atualize antes de decidir",ORANGE);button(box,"Ver evolução por mês",()->FinanceInvestments.months(f,values,capital,0),false);}else note(box,f.cdiError==null?"O gráfico de CDI precisa de uma consulta à taxa. A cópia local não acessa a internet.":f.cdiError);
  if(draft.simulation){note(box,"Simulação concluída. Nenhum saldo foi alterado.");return;}
  Form form=new Form(f.requireContext());Spinner mode=form.select("Como esse valor entra no seu financeiro?",Arrays.asList("Já tenho este valor total investido","Fiz este novo aporte agora"));mode.setSelection(CommandRouter.normalize(f.assistantText).contains("tenho")?0:1);List<Account> accounts=new ArrayList<>(),cash=new ArrayList<>();List<String> labels=new ArrayList<>(),cashNames=new ArrayList<>();for(Account a:current.accounts)if(a.kind==AccountKind.INVESTMENT){accounts.add(a);labels.add(a.name);}else{cash.add(a);cashNames.add(a.name);}labels.add("Criar outra aplicação CDI");Spinner target=form.select("Qual aplicação?",labels),source=form.select("Se foi um aporte, saiu de qual conta?",cashNames);form.moneyField("percent","Percentual contratado do CDI (%)",String.valueOf(draft.cdiPercent));CheckBox plan=draft.monthlySpecified?form.check("Usar "+Money.format(draft.monthly)+" no plano mensal da aplicação principal",false):null;note(form.body,"‘Já tenho’ atualiza o saldo total da aplicação escolhida. ‘Novo aporte’ transfere da conta para o investimento. Nada é comprado no banco.");form.scroll.removeView(form.body);add(output,form.body,12);String operation=f.assistantOperation,today=f.today();
  button(output,"Revisar lançamento",()->{InvestmentEntryPlan entry=new InvestmentEntryPlan();entry.amount=draft.amount;entry.monthly=draft.monthly;entry.updateMonthly=plan!=null&&plan.isChecked();entry.existingBalance=mode.getSelectedItemPosition()==0;entry.accountId=target.getSelectedItemPosition()==accounts.size()?null:accounts.get(target.getSelectedItemPosition()).id;entry.cashId=cash.get(source.getSelectedItemPosition()).id;entry.cdiPercent=FinanceForms.rate(form,"percent");FinanceState before=f.state(),after=before.copy();entry.apply(after,operation,today);Form review=new Form(f.requireContext());note(review.body,(entry.existingBalance?"Definir o saldo total investido como ":"Registrar novo aporte de ")+Money.format(entry.amount)+".\nAplicação: "+labels.get(target.getSelectedItemPosition())+"\nRendimento: "+FinanceInvestments.percent(entry.cdiPercent)+" do CDI");Summary a=summarize(before,today),b=summarize(after,today);note(review.body,"Saldo: "+Money.format(a.cash)+" → "+Money.format(b.cash)+"\nInvestido: "+Money.format(a.invested)+" → "+Money.format(b.invested));if(entry.updateMonthly)note(review.body,"Plano mensal: "+Money.format(entry.monthly));review.dialog("Confira antes de salvar","Confirmar",d->f.mutate(state->{sameRevision(state,before.revision);entry.apply(state,operation,today);},d,()->{f.assistantText="";f.assistantOperation=null;f.home();}));},true);
 }
 private void simulate(List<OrganizerCommand> commands){
  FinanceState state=f.state();boolean needsCdi=false;for(OrganizerCommand c:commands)if(Double.isNaN(c.annualRate))for(Account a:state.accounts)if(InvestmentProjection.CDI.equals(a.yieldIndex))needsCdi=true;
  if(needsCdi){busy(true);new CdiRepository(f.requireContext()).refresh(false,(quote,message)->{if(!active())return;f.cdi=quote;f.cdiError=message;simulationResult(commands);});}else simulationResult(commands);
 }
 private void simulationResult(List<OrganizerCommand> commands){
  if(!active())return;busy(false);output.removeAllViews();FinanceState state=f.state();String today=f.today();
  try{for(OrganizerCommand command:commands){
   long monthly=command.action==OrganizerCommand.Action.REQUIRED_CONTRIBUTION?InvestmentProjection.requiredPortfolioMonthly(state,command.amount,command.annualRate,command.months,f.cdi,today):command.amountSpecified||command.amount>0?command.amount:plannedContribution(state,state.settings.salaryCents);
   double[] values=InvestmentProjection.portfolio(state,monthly,command.annualRate,command.months,f.cdi,today),capital=InvestmentProjection.capital(summarize(state,today).invested,monthly,command.months);
   LinearLayout box=hero(output);eyebrow(box,command.action==OrganizerCommand.Action.REQUIRED_CONTRIBUTION?"APORTE MENSAL ESTIMADO":"ESTIMATIVA BRUTA EM "+command.months+" MESES");add(box,text(box.getContext(),Money.format(command.action==OrganizerCommand.Action.REQUIRED_CONTRIBUTION?monthly:Math.round(values[command.months]*100)),30,WHITE,true),8);
   note(box,"Partindo de "+Money.format(summarize(state,today).invested)+" e aportando "+Money.format(monthly)+"/mês na aplicação principal.");if(command.action==OrganizerCommand.Action.REQUIRED_CONTRIBUTION)note(box,"Meta: "+Money.format(command.amount)+" em "+command.months+" meses.");add(box,new FinanceChart(box.getContext(),values,capital,null,null),8);button(box,"Ver evolução por mês",()->FinanceInvestments.months(f,values,capital,0),false);
   note(box,Double.isNaN(command.annualRate)?"Cada aplicação usa sua taxa cadastrada, mantida constante.":"Hipótese desta simulação: "+FinanceInvestments.percent(command.annualRate)+" a.a. para o total investido.");if(Double.isNaN(command.annualRate)&&f.cdi!=null&&state.accounts.stream().anyMatch(a->InvestmentProjection.CDI.equals(a.yieldIndex))){note(box,"CDI do BCB: "+FinanceScreens.displayDate(f.cdi.date)+". Base 252 dias úteis/ano e 21 por mês.");if(f.cdi.stale(today))pill(box,"Cotação antiga: revise antes de decidir",ORANGE);if(f.cdiError!=null)note(box,f.cdiError);}
   note(box,"Aportes ao fim do mês. Sem impostos, custos ou inflação. Retorno não garantido. Nenhum saldo ou plano de aporte foi alterado.");
  }reveal();}catch(Exception e){error(e.getMessage());}
 }
 void close(){closed=true;if(request!=null)request.cancel();}
}
