package com.example.organizadoria.financeiro.ui;
import android.content.Intent;
import android.net.Uri;
import android.widget.*;
import com.example.organizadoria.financeiro.domain.*;
import com.example.organizadoria.financeiro.network.BcbCdiService;
import java.util.*;
import static com.example.organizadoria.financeiro.domain.FinanceState.*;
import static com.example.organizadoria.financeiro.domain.FinanceEngine.*;
import static com.example.organizadoria.financeiro.ui.FinanceUi.*;
final class FinanceInvestments {
 static String percent(double value){return String.format(new Locale("pt","BR"),"%.2f%%",value);}
 static Account selected(FinanceFragment f,FinanceState s){for(Account a:s.accounts)if(a.id.equals(f.investmentAccount)&&a.kind==AccountKind.INVESTMENT)return a;f.investmentAccount=INVEST;return account(s,INVEST);}
 static long monthly(FinanceFragment f,FinanceState s,Account a){return f.monthlyOverride>=0?f.monthlyOverride:INVEST.equals(a.id)?plannedContribution(s,s.settings.salaryCents):0;}
 static void render(FinanceFragment f,LinearLayout p,FinanceState s){
  f.title("Investimentos");Summary x=summarize(s,f.today());Account a=selected(f,s);LinearLayout hero=hero(p);eyebrow(hero,"PATRIMÔNIO INVESTIDO");add(hero,text(p.getContext(),Money.format(x.invested),32,WHITE,true),8);section(hero,"Aporte do ciclo","Ajustar",()->FinanceForms.contribution(f));add(hero,text(p.getContext(),Money.format(x.contributions)+" realizados · "+Money.format(x.pendingContributions)+" pendentes",13,CYAN,true),0);
  List<Account> investments=new ArrayList<>();for(Account item:s.accounts)if(item.kind==AccountKind.INVESTMENT)investments.add(item);
  if(investments.size()>1){String[] names=new String[investments.size()];int chosen=0;for(int i=0;i<names.length;i++){names[i]=investments.get(i).name;if(investments.get(i).id.equals(a.id))chosen=i;}segments(p,names,chosen,index->{f.investmentAccount=investments.get(index).id;f.monthlyOverride=-1;f.render();});}
  section(p,"Seu dinheiro no tempo","Ajustar taxa",()->profile(f,a));if(investments.size()>1)note(p,a.name+" · "+Money.format(balance(s,a.id,f.today()))+" hoje");
  if(InvestmentProjection.CDI.equals(a.yieldIndex)){LinearLayout source=column(p.getContext());add(p,source,8);section(source,percent(a.yieldPercent)+" do CDI",f.cdiLoading?"Consultando…":"Atualizar",()->f.refreshCdi(true));if(f.cdi!=null){note(source,"Projeção: "+percent(InvestmentProjection.annual(a,s,f.cdi))+" a.a.\nCDI base: "+percent(f.cdi.annualPercent())+" a.a. · BCB, "+FinanceScreens.displayDate(f.cdi.date));if(f.cdi.stale(f.today()))pill(source,"Cotação antiga: revise antes de decidir",ORANGE);}else note(source,f.cdiLoading?"Consultando o CDI…":"Aguardando a taxa para calcular.");if(f.cdiError!=null)note(source,f.cdiError);}
  else pill(p,(a.yieldIndex==null?"Hipótese inicial · ":"Taxa personalizada · ")+percent(InvestmentProjection.annual(a,s,null))+" a.a.",CYAN);
  try{projection(f,p,s,a);}catch(IllegalArgumentException|IllegalStateException e){note(p,e.getMessage());}
  section(p,"Movimentar","Contas",()->f.open("accounts"));button(p,"Registrar aporte",()->contribution(f,a),true);button(p,"Contar um investimento ao Cogni",()->f.open("assistant"),false);
  row(p,"Resgatar ou atualizar","Mantenha o valor real das suas aplicações","›",MUTED,()->FinanceForms.alert(f,"Sua aplicação").setItems(new String[]{"Registrar resgate","Atualizar saldo atual","Adicionar outra aplicação"},(d,index)->{if(index==0)FinanceForms.withdrawal(f);else if(index==1)FinanceForms.accountBalance(f,a.id);else FinanceForms.account(f);}).show());
  section(p,"Aportes realizados","Extrato",()->f.open("statement"));List<Entry> entries=new ArrayList<>(s.entries);entries.sort(Comparator.comparing((Entry e)->e.date).reversed());int count=0;for(Entry e:entries)if(!e.voided&&e.kind==Kind.CONTRIBUTION&&a.id.equals(e.toAccountId)){FinanceScreens.entryRow(f,p,e);if(++count==4)break;}if(count==0)note(p,"Seus aportes confirmados aparecerão aqui.");
  if(InvestmentProjection.CDI.equals(a.yieldIndex)&&!f.cdiAttempted)p.post(()->{if(f.isAdded()&&f.getView()!=null)f.refreshCdi(false);});
 }
 private static void projection(FinanceFragment f,LinearLayout p,FinanceState s,Account a){
  double annual=InvestmentProjection.annual(a,s,f.cdi);long initial=Math.max(0,balance(s,a.id,f.today())),monthly=monthly(f,s,a);int months=f.projectionMonths;
  segments(p,new String[]{"1 ano","5 anos","10 anos","Outro"},months==12?0:months==60?1:months==120?2:3,index->{if(index<3){f.projectionMonths=new int[]{12,60,120}[index];f.render();}else horizon(f);});
  long other=Math.addExact(monthly,20000);double[] values=InvestmentProjection.series(initial,monthly,annual,months),capital=InvestmentProjection.capital(initial,monthly,months),alternative=f.compareProjection?InvestmentProjection.series(initial,other,annual,months):null;
  LinearLayout box=card(p);eyebrow(box,"ESTIMATIVA BRUTA EM "+months+" MESES");TextView total=text(p.getContext(),Money.format(Math.round(values[months]*100)),30,WHITE,true);add(box,total,8);TextView selected=text(p.getContext(),"Mês "+months+" · "+Money.format(Math.round((values[months]-capital[months])*100))+" de rendimento estimado",12,CYAN,false);add(box,selected,6);
  add(box,new FinanceChart(p.getContext(),values,capital,alternative,index->{total.setText(Money.format(Math.round(values[index]*100)));selected.setText((index==0?"Hoje":"Mês "+index)+" · "+Money.format(Math.round((values[index]-capital[index])*100))+" de rendimento estimado");}),12);
  note(box,"● Azul claro: projeção · Cinza: capital aportado"+(alternative==null?"":"\n● Azul: cenário com +R$200/mês"));
  inlineMetrics(box,new String[]{"Capital aportado","Retorno estimado"},new String[]{Money.format(Math.round(capital[months]*100)),Money.format(Math.round((values[months]-capital[months])*100))},new int[]{MUTED,CYAN});if(alternative!=null)note(box,"Com "+Money.format(other)+"/mês: "+Money.format(Math.round(alternative[months]*100))+" ao final.");button(box,"Ver mês a mês",()->months(f,values,capital,0),false);
  section(p,"E se eu aportar mais?","Digitar valor",()->monthly(f,monthly));TextView amount=text(p.getContext(),Money.format(monthly)+" por mês",24,WHITE,true);add(p,amount,4);SeekBar slider=new SeekBar(p.getContext());int steps=(int)Math.min(2000,Math.max(20,monthly/5000*2));slider.setMax(steps);slider.setProgress((int)Math.min(steps,monthly/5000));slider.setProgressTintList(android.content.res.ColorStateList.valueOf(CYAN));slider.setThumbTintList(android.content.res.ColorStateList.valueOf(CYAN));slider.setContentDescription("Aporte mensal da simulação, em passos de 50 reais");slider.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar bar,int v,boolean user){if(user){f.monthlyOverride=v*5000L;amount.setText(Money.format(f.monthlyOverride)+" por mês");}}public void onStartTrackingTouch(SeekBar v){}public void onStopTrackingTouch(SeekBar v){f.render();}});add(p,slider,12);
  CheckBox compare=new CheckBox(p.getContext());compare.setText("Comparar com +R$200 por mês");compare.setTextColor(WHITE);compare.setChecked(f.compareProjection);compare.setOnCheckedChangeListener((v,b)->{f.compareProjection=b;f.render();});add(p,compare,12);note(p,"Mover o controle só altera a simulação. Seu plano de aporte continua igual.");if(f.monthlyOverride>=0)button(p,"Voltar ao aporte do meu plano",()->{f.monthlyOverride=-1;f.render();},false);
  button(p,"Quanto preciso para minha meta?",()->target(f,initial,annual,months),false);row(p,"Comparação personalizada","Compare aportes e taxas diferentes","›",MUTED,()->FinanceForms.simulation(f,false));
  note(p,(InvestmentProjection.CDI.equals(a.yieldIndex)?"CDI observado mantido constante; base de 252 dias úteis/ano e 21 por mês, sem calendário de feriados. ":"Taxa anual efetiva mantida constante. ")+"Aportes ao fim do mês. Valores brutos, sem impostos, custos ou inflação. Estimativa, não retorno garantido.");if(InvestmentProjection.CDI.equals(a.yieldIndex))button(p,"Consultar a fonte do CDI",()->f.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(BcbCdiService.ENDPOINT))),false);
 }
 static void profile(FinanceFragment f,Account a){Form form=new Form(f.requireContext());Spinner type=form.select("Como este dinheiro rende?",Arrays.asList("CDI · percentual contratado","Taxa personalizada · percentual ao ano"));type.setSelection(InvestmentProjection.CDI.equals(a.yieldIndex)?0:1);form.moneyField("rate","Percentual (% do CDI ou % ao ano)",InvestmentProjection.CDI.equals(a.yieldIndex)?String.valueOf(a.yieldPercent):String.valueOf(InvestmentProjection.annual(a,f.state(),null)));int[] previous={type.getSelectedItemPosition()};type.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,android.view.View v,int i,long id){if(previous[0]!=i){form.inputs.get("rate").setText(i==0?"100":String.valueOf(f.state().settings.expectedAnnualReturn));previous[0]=i;}}});note(form.body,"CDI: 100 significa 100% do índice. Use o percentual do seu produto. Taxa personalizada: retorno anual esperado. Só altera a projeção.");form.dialog("Rendimento da aplicação","Salvar",d->{String index=type.getSelectedItemPosition()==0?InvestmentProjection.CDI:InvestmentProjection.FIXED;double rate=FinanceForms.rate(form,"rate");f.mutate(s->InvestmentProjection.profile(account(s,a.id),index,rate),d);});}
 private static void horizon(FinanceFragment f){Form form=new Form(f.requireContext());form.numberField("months","Prazo em meses",String.valueOf(f.projectionMonths));form.dialog("Quanto tempo?","Simular",d->{int months=FinanceForms.integer(form,"months");Projection.calculate(0,0,0,months);f.projectionMonths=months;d.dismiss();f.render();});}
 private static void monthly(FinanceFragment f,long current){Form form=new Form(f.requireContext());form.moneyField("monthly","Aporte da simulação (R$)",Money.input(current));form.dialog("E se eu aportar…","Simular",d->{long value=FinanceForms.value(form,"monthly");Projection.calculate(0,value,0,1);f.monthlyOverride=value;d.dismiss();f.render();});}
 private static void target(FinanceFragment f,long initial,double annual,int months){Form form=new Form(f.requireContext());form.moneyField("target","Quanto quero alcançar (R$)","100000,00");form.numberField("months","Em quantos meses?",String.valueOf(months));note(form.body,"Partindo de "+Money.format(initial)+" a "+percent(annual)+" a.a.");form.dialog("Sua próxima conquista","Calcular",d->{long target=FinanceForms.value(form,"target");int period=FinanceForms.integer(form,"months");long required=Projection.requiredMonthly(initial,target,annual,period);d.dismiss();Form result=new Form(f.requireContext());eyebrow(result.body,"APORTE MENSAL ESTIMADO");add(result.body,text(result.context,Money.format(required),30,CYAN,true),12);note(result.body,"Para "+Money.format(target)+" em "+period+" meses. Sem impostos, custos ou inflação. Retorno não garantido.");add(result.body,new FinanceChart(result.context,InvestmentProjection.series(initial,required,annual,period),InvestmentProjection.capital(initial,required,period),null,null),8);result.dialog("O caminho até sua meta","Fechar",dialog->dialog.dismiss());});}
 static void months(FinanceFragment f,double[] values,double[] capital,int start){Form form=new Form(f.requireContext());int end=Math.min(values.length,start+24);for(int i=start;i<end;i++)row(form.body,i==0?"Hoje":"Mês "+i,"Capital: "+Money.format(Math.round(capital[i]*100))+" · Retorno: "+Money.format(Math.round((values[i]-capital[i])*100)),Money.format(Math.round(values[i]*100)),CYAN,null);note(form.body,"Valores brutos estimados, sem impostos ou taxas.");form.dialog("Evolução mês a mês",end<values.length?"Próximos meses":"Fechar",d->{d.dismiss();if(end<values.length)months(f,values,capital,end);});}
 static void contribution(FinanceFragment f,Account a){FinanceState state=f.state();Form form=new Form(f.requireContext());form.moneyField("value","Valor realizado (R$)","");form.dateField("date","Data do aporte",f.today());List<Account> cash=new ArrayList<>();List<String> names=new ArrayList<>();for(Account c:state.accounts)if(c.kind==AccountKind.CASH){cash.add(c);names.add(c.name);}Spinner source=cash.size()>1?form.select("Saiu de qual conta?",names):null;List<Forecast> plans=new ArrayList<>();List<String> labels=new ArrayList<>();labels.add("Aporte adicional, sem previsão");for(Forecast plan:pending(state))if(plan.kind==Kind.CONTRIBUTION&&a.id.equals(plan.targetAccountId)){plans.add(plan);labels.add(plan.title+" · "+Money.format(remaining(state,plan)));}Spinner selected=plans.isEmpty()?null:form.select("Abater do aporte planejado",labels);if(selected!=null&&plans.size()==1)selected.setSelection(1);note(form.body,"Destino: "+a.name+". A diferença do aporte planejado continua pendente.");String entry=id();form.dialog("Registrar aporte","Registrar",d->{long value=FinanceForms.value(form,"value");String date=form.value("date"),from=cash.get(source==null?0:source.getSelectedItemPosition()).id;int choice=selected==null?0:selected.getSelectedItemPosition();String plan=choice==0?null:plans.get(choice-1).id;if(plan!=null&&!from.equals(plans.get(choice-1).accountId))throw new IllegalArgumentException("A previsão selecionada usa outra conta de origem. Escolha essa conta ou registre um aporte adicional.");String origin=from;f.mutate(s->record(s,entry,Kind.CONTRIBUTION,"Aporte · "+a.name,value,date,origin,a.id,plan,false,f.today()),d);});}
}
